name: Build assets

on:
  push:
    branches-ignore:
      - main
    paths:
      - "**.js"
      - "**.css"
      - "**.vue"
      - "package.json"

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - run: npm install
      - run: npm run prod
      - name: Commit built assets
        continue-on-error: true
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add public/
          git commit -m "Build front-end assets"
          git push
